# -*- coding: utf-8 -*-
"""FooEnv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LChOUGUnUz8ar2_mMrX26Td1MIyuvLIc
"""

import sys
from contextlib import closing
import numpy as np
from io import StringIO

class FooEnv(object):
    def __init__(self,real_time):
        self.real_time=real_time
        nA = 2
        nS = 3
    def inc(self,s, a, real_time):
      time=self.real_time
      self.real_time=time
      trans=[[0.94533, 0.05452, 0.00015],
                       [0.1324, 0.8292, 0.03840],
                       [0.04433, 0.04159, 0.91408]]
      if a == 0:
        s = np.random.choice(3,1, p=trans[s][:])[0]
      elif a==1:
        s= max(s-2,0)
      return s

    def update_probability_matrix(self, s, action,real_time):
      newstate= self.inc(s, action,real_time)
      time=self.real_time
      if time <=399:
        if action == 0:
          reward = 0
          done= False
        elif action == 1:
          reward = -40
          done= False              
      elif time >=399:
        reward = 0
        done= True 
      return newstate, reward, done



